spring:
  application:
    name: config-client-new
  cloud:
    config:
      profile: dev
      label: master
      name: zbb
      discovery:
        enabled: true
        service-id: config-server-new
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://192.168.17.60:9876/eureka/
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
