spring:
  application:
    name: service-zuul-client
  cloud:
    config:
      profile: dev
      label: master
      name: 
      discovery:
        enabled: true
        service-id: config-server-new
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://192.168.17.60:9876/eureka/
  instance:
    prefer-ip-address: true
